export const Type = {
    SESSION_ID_UPDATE: '@jt/SESSION_ID_UPDATE',
    LOCALE_UPDATE: '@jt/LOCALE_UPDATE',
    LANGUAGE_UPDATE: '@jt/LANGUAGE_UPDATE',
    COUNT_UPDATE: '@jt/COUNT_UPDATE',
    STORE_DATA: '@jt/STORE_DATA'
}
